### PR TITLE
Create ko.json

### PR DESCRIPTION
**Pull request by totoromaum**

### CODE REVIEW

**Comment by otacke** [comment]
@totoromaum Just noticed that you're burning through all the H5P content types in order to create the Korean translations and wanted to say: Thanks, buddy!

**Comment by totoromaum** [comment]
@otacke Hi, thank you very much for the warm comments: your comments gave big cheers to me! H5P means a lot to me, and I am offering training sessions to Korean teachers. I believe there will an H5P big bang moment in Korea soon!

**Comment by otacke** [comment]
@totoromaum There are great H5P related things coming from Korea already! See https://kidsloop.net/

**Comment by totoromaum** [comment]
@otacke Thank you for introducing the kidsloop site. I am working for a public sector, and I can see private sectors such as kidsloop are moving fast. The site will help me publicize the strengths of H5P to my colleagues. Starting the end of this year, K-12 school teachers in Busan, Korea will begin to create course wares using H5P. Thank you. Have a great one!

**Pull request merged**
